### ISSUE TITLE
Zeebe client continues to re-connect after thrown exception

### ISSUE THREAD

**Issue by kbakk** [JonatanMartens/pyzeebe#74]
**Describe the bug**
I'm trying to set up a FastAPI with an endpoint that creates a Zeebe job (see example in [gist](https://gist.github.com/kbakk/5bd03c75d798b418d5f9e8e275809583#file-main-py)). 

If Zeebe is unavailable, it will return a 500 error to the client (raise `pyzeebe.exceptions.zeebe_exceptions.ZeebeGatewayUnavailable`). This is expected. However, it should not try to retry the connection, after the exception has been raised. 

```
...
    self._common_zeebe_grpc_errors(rpc_error)
  File "/Users/kristofferb/Code/temp/uvicorn-zeeebe-issue/.venv/lib/python3.7/site-packages/pyzeebe/grpc_internals/zeebe_adapter_base.py", line 71, in _common_zeebe_grpc_errors
    raise ZeebeGatewayUnavailable()
pyzeebe.exceptions.zeebe_exceptions.ZeebeGatewayUnavailable
[2020-11-03 13:25:50,361] [81833 - Thread-3] [DEBUG] pyzeebe.grpc_internals.zeebe_adapter_base - Grpc channel connectivity changed to: ChannelConnectivity.CONNECTING
[2020-11-03 13:25:50,361] [81833 - Thread-3] [DEBUG] pyzeebe.grpc_internals.zeebe_adapter_base - Connecting to localhost:26599.
[2020-11-03 13:25:50,362] [81833 - Thread-4] [DEBUG] pyzeebe.grpc_internals.zeebe_adapter_base - Grpc channel connectivity changed to: ChannelConnectivity.TRANSIENT_FAILURE
[2020-11-03 13:25:50,362] [81833 - Thread-4] [WARNING] pyzeebe.grpc_internals.zeebe_adapter_base - Lost connection to localhost:26599. Retrying...
...
```

Full log output in gist. 

**To Reproduce**
I've created this [gist](https://gist.github.com/kbakk/5bd03c75d798b418d5f9e8e275809583#file-readme-md) with steps to reproduce:

```sh
git clone https://gist.github.com/kbakk/5bd03c75d798b418d5f9e8e275809583 pyzeebe-fastapi
```

Then follow the steps in the README.md.

Note that I'm not able to reproduce this, when Uvicorn is running under Gunicorn ([recommended for production setup](https://www.uvicorn.org/#running-with-gunicorn)). I am not certain why though, it could have something to do with how Gunicorn treats the request session. 

**Expected behavior**
Once the exception is raised, the `ZeebeClient` instance _should be_ deleted – i.e. not in any scopes anymore – and shouldn't continue to retry connection to Zeebe broker.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7

**Comment by JonatanMartens** [comment]
Would you expect the `ZeebeClient`/`ZeebeWorker` to stop immediately after encountering the exception? Or do you think it should retry based on configuration?

**Comment by kbakk** [comment]
I think [the behavior of the Node JS client](https://github.com/zeebe-io/zeebe-client-node-js#client-side-retry) makes sense. 

But before the exception is thrown by the library, I would expect it to stop all retries/not persist any processing threads.

**Comment by JonatanMartens** [comment]
#75 should fix this. Do you want to review the changes @kbakk ?

**Comment by kbakk** [comment]
@JonatanMartens I will take a look on Friday if that's ok (a bit busy at the moment).

**Comment by kbakk** [comment]
Also, thank you so much for looking into this!
