### ISSUE TITLE
Worker threads silently die and stop handling pending jobs after an exception occurs

### ISSUE THREAD

**Issue by CodechCFA** [JonatanMartens/pyzeebe#80]
**Describe the bug**
Worker threads seem to silently die out and stop handling pending jobs after an exception occurs, such as `ZeebeBackPressure`

**To Reproduce**
1. Run a worker with any number of tasks.
2. Trigger a workflow that runs those tasks a few times and force any exception, in my case I forced `ZeebeBackPressure`. Either some tasks will be handled and others won't or it will just sit there and never handle the pending jobs. You can see this happening because the debug logs for a task will stop logging the periodic `Activating jobs for task:`.  Shutting down and then restarting the worker after that will process all pending jobs. 

**Expected behavior**
The worker should continually process all incoming jobs even if an exception occurs. Or if an exception occurs, the system exits.

**Desktop (please complete the following information):**
 - OS: Debian (Buster)
 - Version 2.2.2

**Comment by kbakk** [comment]
> in my case I forced `ZeebeBackPressure`

@CodechCFA Do you have a way to reproduce? Is there some way I can set up Zeebe to cause this?

**Comment by CodechCFA** [comment]
Easiest way is to set the backpressure.fixed.limit to a small number like 1 and then fire off some workflows.

https://docs.zeebe.io/appendix/broker-config-template.html

Make sure the algorithm is left on its default of "fixed".

I'm currently working around this by managing the threads myself and re-implementing `_handle_task` to catch any exceptions that happen and then exiting the script with an error. This allows containerized workloads using pyzeebe to just restart the container and fire up all of the threads again.

```python
def _handle_task(task: Task) -> None:
    try:
        logger.debug(f"Handling task {task}")
        while not worker.stop_event.is_set() and worker.zeebe_adapter.connected or worker.zeebe_adapter.retrying_connection:
            if worker.zeebe_adapter.retrying_connection:
                logger.info(f"Retrying connection to {worker.zeebe_adapter.connection_uri or 'zeebe'}")
                continue

            _handle_jobs(task)

        logger.warning(f"LOOP EXITED FOR TASK: {task.type}.")
    except:
        traceback.print_exc(file=sys.stdout)
        logger.warning("Exiting due to exception from activating jobs")

    worker.stop()
```

**Comment by kbakk** [comment]
A follow-up here, having investigated the issue further.

The issue reproduces with the following setup:

```py
import logging
import time

from pyzeebe.worker.worker import ZeebeWorker

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger()
worker = ZeebeWorker()


@worker.task(task_type="sleep")
def sleep_task():
    logger.debug("starting sleep")
    time.sleep(5)
    logger.debug("sleep ended")
    return {}


@worker.task(task_type="x")
def x_task():
    return {}


logger.debug("starting worker...")
worker.work()
logger.debug("worker started, threads preventing to exit")
```

And changing the broker as suggested (e.g. modify [this](https://github.com/zeebe-io/zeebe-docker-compose/blob/master/broker-only/application.yaml) with below changes and start the corresponding docker-compose file):

```yaml
...
    backpressure:
      enabled: true
      algorithm: "fixed"
      fixedLimit:
        limit: 1
    # this can be commented out, as it makes logging very verbose at times
    exporters:
      debuglog:
        className: io.zeebe.broker.exporter.debug.DebugLogExporter
        args:
          logLevel: debug
          prettyPrint: false
```

I've also created a workflow ([sleep.bpmn](https://github.com/JonatanMartens/pyzeebe/files/5658911/sleep.bpmn.zip)) that creates a job every 10 sec

![image](https://user-images.githubusercontent.com/24817039/101477488-94686000-394f-11eb-9f2b-477cdb8a266b.png)

Starting 1 process of the worker doesn't seem to immediatly reproduce it, so I'm starting the script in two different terminals. After a few seconds one of them will throw an exception:


```py
Exception in thread ZeebeWorker-Task-sleep:
Traceback (most recent call last):
  File "lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "pyzeebe/worker/worker.py", line 81, in _handle_task
    self._handle_jobs(task)
  File "pyzeebe/worker/worker.py", line 84, in _handle_jobs
    for job in self._get_jobs(task):
  File "pyzeebe/grpc_internals/zeebe_job_adapter.py", line 32, in activate_jobs
    self._common_zeebe_grpc_errors(rpc_error)
  File "pyzeebe/grpc_internals/zeebe_adapter_base.py", line 76, in _common_zeebe_grpc_errors
    raise rpc_error
  File "pyzeebe/grpc_internals/zeebe_job_adapter.py", line 23, in activate_jobs
    fetchVariable=variables_to_fetch, requestTimeout=request_timeout)):
  File "lib/python3.7/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "lib/python3.7/site-packages/grpc/_channel.py", line 706, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
      status = StatusCode.UNKNOWN
      details = ""
      debug_error_string = "{"created":"@1607439215.201351000","description":"Error received from peer ipv6:[::1]:26500","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"","grpc_status":2}"
```

Note that if I comment out the `x` task definition, it will not die silently but exit. It makes sense, as when that's the only task, it's just one thread that lives after the `logger.debug("worker started, threads preventing to exit")` line (except when a job is running), so when that dies, the Python program exits. If there's two threads (one for `sleep`, one for `x`) and one of them dies, the other thread will keep the application active.

What seems to happen is that there's a thread for each task. It ensures that jobs are pulled from the broker:

https://github.com/JonatanMartens/pyzeebe/blob/f83e992ede6fb11e80ebb2cb460bd295b2307947/pyzeebe/worker/worker.py#L79

In case this fails, there's no exception guard on [`_handle_task`](https://github.com/JonatanMartens/pyzeebe/blob/f83e992ede6fb11e80ebb2cb460bd295b2307947/pyzeebe/worker/worker.py#L62). So if there's an error thrown there, the thread will close. After it closes, there's nothing that ensures that it is spun up again.

I think there's a few ways to handle this. Here's two:

1) Have [`_handle_task`](https://github.com/JonatanMartens/pyzeebe/blob/f83e992ede6fb11e80ebb2cb460bd295b2307947/pyzeebe/worker/worker.py#L62) do a try/except, and only log the exception in the while loop, don't exit the loop if it fails.
2) Have a watcher thread that ensures that the thread continues to run, and restarts it if it doesn't.

In any case, there should probably be a `max_number_of_failures` variable that tells pyzeebe to exit if that is exceeded.

@JonatanMartens Do you have any preference for the above? I can try to put together a PR for this (unfortunately, I'm a bit swamped with work  at the moment, so I can't promise when I will have that in place).

**Comment by CodechCFA** [comment]
I initially implemented the try/except -> log approach you mentioned in 1 but I realized I wanted these exceptions to bubble to the top in order for error trackers such as sentrio.io to record these events, which led me to the route of just exiting the system during those events. Given that, I would vote for option 2. It might be worth it to have a configuration flag that lets the user choose which option they want. I'm a bit swamped as well but when things start to slow down I wouldn't mind handling this PR.

**Comment by JonatanMartens** [comment]
I think option 2 would be preferred for the reasons mentioned above. `max_number_of_failures` is definitely a must. 
However, I don't think that pyzeebe should stop all threads if it encounters an error on one task. I would expect the worker to continue polling for the other tasks. 

Sorry for my late reply (I've also been pretty busy lately).

**Comment by kbakk** [comment]
@CodechCFA @JonatanMartens I've started work on this in #112. It's not done yet - e.g. lacking tests (not quite sure how to go about this), and handling consecutive errors. I'd appreciate if you could take a look and come with feedback and suggestions. And let's move the discussion over there.
