### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by kbakk** [JonatanMartens/pyzeebe#84]
**Is your feature request related to a problem? Please describe.**
Python 3.5 is EOL as of September 13. 2020 ([announcement](https://pythoninsider.blogspot.com/2020/10/python-35-is-no-longer-supported.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+PythonInsider+%28Python+Insider%29)). 

**Describe the solution you'd like**
Remove 3.5/update to 3.6 here

https://github.com/JonatanMartens/pyzeebe/blob/f83e992ede6fb11e80ebb2cb460bd295b2307947/setup.py#L26
https://github.com/JonatanMartens/pyzeebe/blob/b08beb4eb433cf1b52fe07adcf73ab4b830ba570/.github%2Fworkflows%2Ftest-python-package.yml#L15
https://github.com/JonatanMartens/pyzeebe/blob/91e4066da2feb818a4f8bdf148478609c0b3a256/.github%2Fworkflows%2Ftest-zeebe-integration.yml#L18
https://github.com/JonatanMartens/pyzeebe/blob/01214cb477244161697852982f063a7f6c7f4b39/docs%2Findex.rst#L49

**Comment by JonatanMartens** [comment]
Merged into development, so closing this now.
