### ISSUE TITLE
how to get “job” variables？

### ISSUE THREAD

**Issue by Explorer1092** [JonatanMartens/pyzeebe#98]
I want to get job object to analyze "variables"
For example, to determine whether variables['is_exist'] exists

```
@worker.task(task_type="subdomain.manager.save", exception_handler=on_error)
def save_task(job: Job):
    variables = json.loads(job.variables)
    if 'is_exist' in variables :
         return variables['is_exist'] 
```
But I found the following error 
```
'variables': {}}. Error: update_task() missing 1 required positional argument: 'job'
```

**Comment by Explorer1092** [comment]
@kbakk @JonatanMartens

**Comment by kbakk** [comment]
@Explorer1092 This won't work, as the task worker is looking for a variable named `job` – it's not getting the `Job` instance as you're expecting. 

I don't think it currently is possible to get the `Job` instance from within a task worker.

Though, you may get what you want here, by looking for an optional parameter:

```py
@worker.task(task_type="subdomain.manager.save", exception_handler=on_error)
def save_task(is_exists=None):
    return {"is_exists": is_exists}
```

_In your example you also don't return a dictionary, see the [docs here on this](https://pyzeebe.readthedocs.io/en/latest/worker_tasks.html#tasks-that-don-t-return-a-dictionary)._


If this is all you're trying to achieve, you might be better off by using FEEL expressions within the Zeebe BPMN:

- https://docs.zeebe.io/reference/expressions.html
- https://camunda.github.io/feel-scala/1.12/

**Comment by Explorer1092** [comment]
how to get “custom header”？

**Comment by kbakk** [comment]
Accessing the headers is not implemented yet unfortunately.

I'd recommend that you create an issue for this if it's something you need. I haven't needed it yet (I'm just passing values as variables) but since it's a "core functionality" of Zeebe it's probably something we should support.

**Comment by JonatanMartens** [comment]
As @kbakk pointed out there currently isn't a solution to receiving headers. You could bypass this by adding a decorator to the task:

```python
def add_headers_to_variables(job: Job):
    job.variables["is_exists"] = job.custom_headers["is_exists"]
    return job

@worker.task(task_type="subdomain.manager.save", exception_handler=on_error, before=[add_headers_to_variables])
def save_task(is_exists):
    return {"is_exists": is_exists}
```

I have opened a new issue for this #100. I would

**Comment by JonatanMartens** [comment]
I'm closing this issue as we'll continue to discuss this in #100.
